package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	composetypes "github.com/compose-spec/compose-go/v2/types"
	"gopkg.in/yaml.v3"
)

// Override describes the engine-side additions we layer onto the
// user's compose project for the primary service. Each field is
// optional (zero value is "no change for that aspect").
type Override struct {
	// Service is the name of the primary service to override; matches
	// devcontainer.json's "service" field.
	Service string

	// Image, when set, replaces the primary service's image and
	// clears its build directive (mutually exclusive in compose).
	// Engine sets this to the feature-extended image tag built
	// upstream.
	Image string

	// ExtraBindMounts are added to the primary service's volumes.
	// Engine adds the workspace folder bind here, plus any mounts
	// declared in devcontainer.json (cfg.Mounts).
	//
	// IMPORTANT: compose v2's default merge strategy for sequence
	// fields is REPLACEMENT, not concatenation. WriteRunOverride
	// reads the existing service's volumes from the loaded project
	// and emits the full merged list so we don't drop the user's
	// declarations.
	ExtraBindMounts []BindMount

	// ExtraEnvironment is merged into the primary service's
	// environment map. Compose merges maps natively, so we only
	// need to emit our additions.
	ExtraEnvironment map[string]string

	// Labels written on the primary service so Engine.Attach's
	// label-based lookup works (`dev.containers.id`, etc.).
	Labels map[string]string
}

// BindMount describes one bind volume in the override.
type BindMount struct {
	Source   string
	Target   string
	ReadOnly bool
}

// WriteBuildOverride writes dst with the build override. Pins the
// primary service's image to ov.Image and clears any inherited
// build: directive via the YAML !reset tag (compose v2 idiom).
//
// Returns an error if ov.Image or ov.Service is empty.
func WriteBuildOverride(dst string, ov Override) error {
	if ov.Service == "" {
		return fmt.Errorf("WriteBuildOverride: ov.Service required")
	}
	if ov.Image == "" {
		return fmt.Errorf("WriteBuildOverride: ov.Image required")
	}

	// Hand-built YAML: the !reset tag is compose-v2 specific and
	// awkward to emit through gopkg.in/yaml.v3's struct path. Inline
	// templating keeps the output deterministic.
	body := fmt.Sprintf(`# Generated by devcontainer-go — do not edit by hand.
# Pins the primary service's image to a tag built by the engine and
# clears any base build: directive (mutually exclusive with image:).
services:
  %s:
    image: %s
    build: !reset null
`, yamlScalar(ov.Service), yamlScalar(ov.Image))

	return writeFile(dst, body)
}

// WriteRunOverride writes dst with the run-time override: workspace
// bind mount, container env, labels. Reads the primary service's
// existing volumes from `project` and emits the full merged list so
// compose v2's "sequence-replace" merge doesn't drop the user's
// declarations.
//
// `project` may be nil; in that case the override emits only our
// declarations (caller asserts no user-declared volumes exist).
func WriteRunOverride(dst string, project *composetypes.Project, ov Override) error {
	if ov.Service == "" {
		return fmt.Errorf("WriteRunOverride: ov.Service required")
	}

	merged, err := mergedVolumes(project, ov)
	if err != nil {
		return err
	}

	doc := map[string]any{
		"services": map[string]any{
			ov.Service: buildServiceOverride(merged, ov),
		},
	}
	body, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshal run override: %w", err)
	}
	return writeFile(dst, "# Generated by devcontainer-go — do not edit by hand.\n"+string(body))
}

// mergedVolumes combines existing volumes from the user's primary
// service with ov.ExtraBindMounts. Existing entries are preserved as-
// is (string CSV form or full object form, whichever the user used).
// New mounts are appended in the order supplied.
func mergedVolumes(project *composetypes.Project, ov Override) ([]any, error) {
	var existing []composetypes.ServiceVolumeConfig
	if project != nil {
		svc, err := PrimaryService(project, ov.Service)
		if err == nil {
			existing = svc.Volumes
		}
	}

	out := make([]any, 0, len(existing)+len(ov.ExtraBindMounts))
	for _, v := range existing {
		out = append(out, serializeServiceVolume(v))
	}
	for _, b := range ov.ExtraBindMounts {
		out = append(out, map[string]any{
			"type":      "bind",
			"source":    b.Source,
			"target":    b.Target,
			"read_only": b.ReadOnly,
		})
	}
	return out, nil
}

// serializeServiceVolume converts a compose-go ServiceVolumeConfig
// into the wire form yaml.Marshal will emit. We use the full object
// form even if the user originally wrote a string ("a:b" CSV) — losing
// the original form is fine since compose accepts either.
func serializeServiceVolume(v composetypes.ServiceVolumeConfig) map[string]any {
	out := map[string]any{
		"type":   v.Type,
		"source": v.Source,
		"target": v.Target,
	}
	if v.ReadOnly {
		out["read_only"] = true
	}
	return out
}

func buildServiceOverride(volumes []any, ov Override) map[string]any {
	svc := map[string]any{}
	if len(volumes) > 0 {
		svc["volumes"] = volumes
	}
	if len(ov.ExtraEnvironment) > 0 {
		// Use a sorted map for deterministic output. yaml.v3 sorts
		// map keys alphabetically by default, but emitting a
		// []yaml.MapItem-equivalent here gives us explicit control
		// for golden tests.
		env := make(map[string]any, len(ov.ExtraEnvironment))
		for _, k := range sortedKeys(ov.ExtraEnvironment) {
			env[k] = ov.ExtraEnvironment[k]
		}
		svc["environment"] = env
	}
	if len(ov.Labels) > 0 {
		labels := make(map[string]any, len(ov.Labels))
		for _, k := range sortedKeys(ov.Labels) {
			labels[k] = ov.Labels[k]
		}
		svc["labels"] = labels
	}
	return svc
}

// yamlScalar quotes a value if it contains characters that would
// require quoting in YAML. Conservative: any non-alphanumeric / dot /
// dash / underscore / slash / colon / @ character triggers quoting.
// (Image refs and service names are well-behaved, but we play it safe.)
func yamlScalar(s string) string {
	for _, c := range s {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' ||
			c >= '0' && c <= '9' ||
			c == '-' || c == '_' || c == '.' || c == '/' ||
			c == ':' || c == '@') {
			return fmt.Sprintf("%q", s)
		}
	}
	return s
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// writeFile writes body to path, creating the parent directory if
// needed. Mode 0644 so users can inspect the generated YAML.
func writeFile(path, body string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return os.WriteFile(path, []byte(body), 0o644)
}
